### ISSUE TITLE
can't find server on mobile app

### ISSUE THREAD

**Issue by mohad12211** [pzmarzly/mic_over_mumble#12]
I'm  using arch linux, everything works good, the virtual mic is there, but I can't see the server on my mobile app, however if I use the script on my laptop which linux mint installed, I can see the server and connect to it. I don't  understand why I can't connect to the server with arch. any ideas?

**Comment by pzmarzly** [comment]
Hi, thanks for being interested in my project!

The issue you are describing is indeed quite weird, but I hope you'll be able to resolve it.

Can you connect to the server by specifying the IP and port manually? I think the default port is 64738, and you can get your IP with `ip addr show` (look for `inet` under `enXXX` and `wlXXX` devices). If you cannot connect, then there may be some issue with firewall config (e.g. `iptables` or `ufw`). Sadly each Arch Linux installation is quite unique, so then you'll need to investigate on your own.

On the other hand, if you can connect manually, then there is something wrong with server discovery, which is done using Apple Bonjour protocol. I have no idea why that wouldn't work, but you can take a look at [Bonjour ports](https://support.apple.com/en-us/HT202944), and, while I'm not sure about it, you may need to install and start `avahi-daemon`. Avahi is an implementation of Bonjour protocol, and while I'm not sure whether Murmur (mumble server) even uses it, it is running by default on Ubuntu, Mint, etc., so that may be it.

Please let me know if you manage to find out something.

**Comment by mohad12211** [comment]
Thanks!
I don't use any firewall on my system, the avahi package is already installed, but it was disabled, so I enabled it and started it, and it worked!
I would suggest adding a part to mention that you need to make sure avahi-daemon is enabled/started if you can't find the server.

**Comment by pzmarzly** [comment]
> so I enabled it and started it, and it worked

That's awesome!

> I would suggest adding a part...

Thanks for the idea! Done in https://github.com/pzmarzly/mic_over_mumble/commit/09928f1f3053b6a1c4b1541a7fa1fc5af7919e42
