### ISSUE TITLE
Why disable mumble-server.service?

### ISSUE THREAD

**Issue by Raphael1347** [pzmarzly/mic_over_mumble#6]
Hi,

I was wondering why we disable mumble-server.service when we install mumble and murmur when following the instruction in the README.

Thank you and good day

**Comment by pzmarzly** [comment]
Thanks for the question.

Enabling/disabling a service, in systemd glossary, means controlling whether it should automatically start when the system boots up. To illustrate, `systemd start mumble-server` starts the server now, `systemd enable mumble-server` does not start it immediately, but will make it start after reboot.

It makes sense for the Ubuntu package `mumble-server` to configure starting murmurd on system launch, as that package is mostly used on servers (Ubuntu Server). But `mic_over_mumble` is going to be mostly installed on regular PCs, where most people prefer to keep their startup dependencies short.

Back when I was writing the script, I assumed that murmurd won't be present already (as that is the case on Arch Linux, as far as I remember). So `mic_over_mumble` automatically starts and stops the server, though it needs the port to be free.

It would absolutely make sense to let users use external Mumble server, which could include one running on `localhost` but not managed by the script. But IMO it shouldn't become the new default, since the default `/etc/mumble-server.conf` configuration may be not the one the user wants (bitrate set to 72kbps, no Bonjour advertisement over LAN). I'm not sure whether it makes more sense to add configuration to the script, or to just let someone who wants it make a fork where the lines about starting & stopping the server are removed.

**Comment by Raphael1347** [comment]
Thank you for the answer
